FROM node:20.10-alpine

ENV NODE_ENV=test

WORKDIR /app

# add package.json and package-lock.json to the container
ADD package.json package-lock.json ./

# Install dependencies
RUN npm install

# Add the rest of the files
ADD bin ./bin
ADD jest.config.js ./jest.config.js

# Run the app
CMD ["npm", "run", "test:watch"]
